//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jogo_Xadrez.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageGame {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageGame() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jogo_Xadrez.Util.MessageGame", typeof(MessageGame).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PEÇA DE ORIGEM ESCOLHIDA NÃO É SUA!.
        /// </summary>
        internal static string msg_A_Peca_De_Origem_Escolhida_Nao_E_Sua {
            get {
                return ResourceManager.GetString("msg_A_Peca_De_Origem_Escolhida_Nao_E_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino:.
        /// </summary>
        internal static string msg_Destino {
            get {
                return ResourceManager.GetString("msg_Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÃO EXISTE PEÇA NA POSIÇÃO DE ORIGEM!.
        /// </summary>
        internal static string msg_Nao_Existe_Peca_Na_Posicao_Origem {
            get {
                return ResourceManager.GetString("msg_Nao_Existe_Peca_Na_Posicao_Origem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÃO HA MOVIMENTOS POSSÍVEIS PARA A PEÇA DE ORIGEM ESCOLHIDA.
        /// </summary>
        internal static string msg_Nao_Ha_Movimentos_Possiveis_Para_A_Peca_De_Origem_Escolhida {
            get {
                return ResourceManager.GetString("msg_Nao_Ha_Movimentos_Possiveis_Para_A_Peca_De_Origem_Escolhida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem: .
        /// </summary>
        internal static string msg_Origem {
            get {
                return ResourceManager.GetString("msg_Origem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSIÇÃO DE DESTINO INVALIDA.
        /// </summary>
        internal static string msg_Posicao_De_Destino_Invalida {
            get {
                return ResourceManager.GetString("msg_Posicao_De_Destino_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSIÇÃO INVALIDA!.
        /// </summary>
        internal static string msg_Posicao_Invalida {
            get {
                return ResourceManager.GetString("msg_Posicao_Invalida", resourceCulture);
            }
        }
    }
}
